#Range: 100 ~ 4096
height = 128
#Range: 50 ~ 1000000
segments = 240
#Range: 1 ~ 10
count = 5
#Range: 12 ~ 100000
radius = 48
#Radius increment between consecutive halo circles
#Range: 10 ~ 1000
interval = 32
increasing = true
color_red = 255.0
color_green = 255.0
color_blue = 255.0
#Range: 0.0 ~ 1.0
color_alpha = 0.85
#Range: > 128
render_distance = 1024

