
#Incinerator's Try Hard Config
["The Incinerator"]
	#Range: 1 ~ 100
	"Charging time (ticks) of The Incinerator" = 30
	#Range: 1 ~ 100
	"(Client Only) Max Charging time (ticks) to Form the Biggest Magic Circle underfoot when charging" = 30
	#Range: 0.0 ~ 1.7976931348623157E308
	"Basic Damage dealt by The Incinerator's Skill" = 100.0
	#Range: 0.0 ~ 100.0
	"Max Health Damage Percentage dealt by The Incinerator's Skill" = 0.5
	#Range: 0.0 ~ 100.0
	"The Radius of the ignis circles released by The Incinerator's Skill" = 6.0

["The Immolator"]
	#Range: 1 ~ 100
	"Charging time (ticks) of The Immolator" = 45
	#Range: 1 ~ 100
	"(Client Only) Max Charging time (ticks) to Form the Biggest Magic Circle underfoot when charging" = 45
	#Range: 0.0 ~ 100.0
	"Max Health Damage Percentage dealt by The Immolator's Skill" = 4.0
	#Range: 0.0 ~ 100.0
	"The Radius of the ignis circles released by The Immolator's Skill" = 25.0
	#Range: 0.0 ~ 1.7976931348623157E308
	"Basic Ignis Circle Damage dealt by The Immolator's Skill" = 6.0
	#Range: 0.01 ~ 250.0
	"[Questionable, maybe unused method] The Radius of the Quake released by The Immolator's Skill" = 6.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"[Questionable, maybe unused method] Quake Damage Multiplier of The Immolator's Skill" = 2.0

["Tidal Claws"]
	#Range: 0.0 ~ 1.7976931348623157E308
	"Tentacle Damage released by Tidal Claws" = 16.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Tentacle's First Detection Range released by Tidal Claws" = 25.0
	#Range: 1.0 ~ 1.7976931348623157E308
	"Tentacle's Second Detection Range released by Tidal Claws" = 25.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Hook's Max Range released by Tidal Claws" = 120.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Hook's Max Speed released by Tidal Claws" = 16.0

["Gauntlet of Bulwark"]
	#Range: 1.0 ~ 1.7976931348623157E308
	"Charge Damage Multiplier Of Gauntlet Of Bulwark" = 14.0

["Bloom Stone Pauldrons"]
	#Range: > 1
	"Cooldown time (ticks) of Bloom Stone Pauldrons to shoot Amethyst Cluster" = 40

["The Annihilator"]
	#Range: 0.01 ~ 1.7976931348623157E308
	"Skill Range Of The Annihilator" = 12.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Skill Damage Multiplier Of The Annihilator" = 8.0
	#Range: 1 ~ 1000
	"Charging time (ticks) of The Annihilator" = 20
	#Range: > 1
	"Skill Cooldown time (ticks) of The Annihilator" = 50

["Gauntlet of Guard"]
	#Range: 0.01 ~ 1.7976931348623157E308
	"Attraction Radius Of Gauntlet Of Guard" = 21.0
	#Range: 0.01 ~ 1.7976931348623157E308
	"Scale of Normalized Attraction Vector Of Gauntlet Of Bulwark" = 0.3

["Cursed Bow"]
	"Whether Cursed Bow can be enchanted on Enchantment Table, and with Infinity and Flaming Arrow" = true

["Cursium Armor"]
	#Range: > 1
	"Skill Cooldown time (ticks) of Cursium Helmet" = 200
	#Range: > 1
	"Skill Cooldown time (ticks) of Cursium Boots" = 200
	#Range: 4.9E-324 ~ 1.7976931348623157E308
	"Skill Speed of Cursium Boots" = 4.9E-324

["Laser Gatling"]
	"Whether Laser Gatling can ignite blocks when used by the player" = true

