#耀魂喷泉模块开关
enableSoulTrapezoid = false
#下界之星增强面板模块开关
enableNetherStarUpgrade = true
#耀魂喷泉门槛
#Range: 100 ~ 10000
soulCost = 1000
#下界之星增加刀面板(需要填充时比期望面板少1)
#Range: 10 ~ 100
maxAttackModifier = 21
#拔刀触发幻影剑技
enableDoSlash = false
#SS后攻击变三段
enabless = false
#快刀无感模块
disable_stun = true
#经验值增伤
xp_add = false
#是否开启持刀无法交互除刀以外的所有的可交互选项功能
disableOtherInteractions = true
#幻影剑倍率模块精炼等级加成系数
#Range: 0.0 ~ 1.0
refinedFactor = 0.0
#幻影剑倍率模块基础攻击修正系数
#Range: 0.0 ~ 1.0
attackModifierFactor = 0.0

