
["Auto-Targeting Setting"]
	#Enable the enemy lock-on switch?[Default:true]
	enablesEnemyLockOnSwitch = true
	#The maximum distance of the crosshair lock-on.[Default:100.0,Original Resharped:40.0]
	#Range: 0.0 ~ 200.0
	crosshairMaxDist = 100.0
	#The maximum angle of the crosshair lock-on.[Default:10.0,Original Resharped:0.0]
	#Range: 0.0 ~ 180.0
	crosshairMaxAngle = 10.0
	#The maximum distance of the nearest lock-on.[Default:32.0,Original Resharped:16.0]
	#Range: 0.0 ~ 200.0
	nearestMaxDist = 32.0
	#The rotation speed of the lock-on.[Default:1.0]
	#Range: 0.0 ~ 8.0
	lockonRotationSpeed = 1.0

