
[HUD]
	#New Crosshair of TaCZ:Labs.
	"Enable TaCZ:Labs Crosshair" = true
	#Default: Bonding a combination of values such as scattering and plane velocity, for better visual experience.
	#On: Based strictly on real scattering values.
	"Diffusion strictly based on real spread" = false
	#Maximum value of collimator spread affected by velocity, range 0 ~ 100, default 100 .
	#Range: 0 ~ 100
	"Max Speed Spread" = 100

	[HUD."Global Settings"]
		#Crosshair RGBA HEX color, format is 0xAARRGGBB.
		#Range: > -2147483648
		"Crosshair Color" = -429064340
		#Range: 0 ~ 255
		A = 230
		#Range: 0 ~ 255
		R = 108
		#Range: 0 ~ 255
		G = 255
		#Range: 0 ~ 255
		B = 108
		#Shadow alpha of crosshair, range 0 ~ 255, default 128.
		#Range: 0 ~ 255
		"Shadow Alpha" = 128
		#Shadow offset of crosshair, range 1 ~ 6, default 1 .
		#Range: 0 ~ 3
		"Shadow Offset" = 1
		#Spread of crosshair, range 0.0 ~ 60.0, default 30.0 .
		#Range: 0 ~ 60
		"Crosshair Spread" = 30
		#Spread of crosshair, range 0.0 ~ , default  .
		#Range: 0 ~ 60
		"Spread Extent" = 30

["Local Settings"]

	["Local Settings"."Crosshair Type"]
		#Crosshair of Pistol
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		Pistol = "RIGHT_ANGLE"
		#Crosshair of Sub-Machine Gun
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		"Sub-Machine Gun" = "CROSSHAIR"
		#Crosshair of Rifle
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		Rifle = "CROSSHAIR"
		#Crosshair of Machine Gun
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		"Machine Gun" = "CROSSHAIR"
		#Crosshair of Sniper
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		Sniper = "CROSSHAIR"
		#Crosshair of Shotgun
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		Shotgun = "RECT"
		#Crosshair of Heavy Weapon
		#Allowed Values: CROSSHAIR, RECT, RIGHT_ANGLE, POINT, TACZ
		"Heavy Weapon" = "RECT"

	["Local Settings"."Crosshair Properties"]
		#Radius of crosshair, range 0 ~ 10, default 5 .
		#Range: 0 ~ 10
		"Crosshair Radius" = 3
		#Length of crosshair, range 1 ~ 20, default 6 .
		#Range: 1 ~ 20
		"Crosshair Length" = 6
		#Width of crosshair, range 1 ~ 10, default 2 .
		#Range: 1 ~ 10
		"Crosshair Width" = 1
		#Radius of rect crosshair, range 0 ~ 20, default 12 .
		#Range: 0 ~ 20
		"Rect Crosshair Radius" = 6
		#Length of rect crosshair, range 1 ~ 20, default 6 .
		#Range: 1 ~ 20
		"Rect Crosshair Length" = 6
		#Width of rect crosshair, range 1 ~ 10, default 1 .
		#Range: 1 ~ 10
		"Rect Crosshair Width" = 1
		#Radius of right angle crosshair, range 0 ~ 10, default 4 .
		#Range: 0 ~ 10
		"Right Angle Crosshair Radius" = 2
		#Width of right angle crosshair, range 1 ~ 5, default 1 .
		#Range: 1 ~ 5
		"Right Angle Crosshair Width" = 1

