#How far (blocks away) you can be before a screen starts rendering it will get a cubed size area of this many blocks in other terms it squares your value here so the screen can create this render distance effect
#Range: 0.0 ~ 1.7976931348623157E308
load_distance = 30.0
#This has been deprecated and doesnt actually do anything anymore! The One above is actually the one to use!
#Range: 0.0 ~ 1.7976931348623157E308
unload_distance = 18.0
#The resolution that minePads should use
#Smaller values produce lower qualities, higher values produce higher qualities
#Due to how web browsers work however, the larger this value is, the smaller text is
#Also, higher values will invariably lag more
#A good goto value for this would be the height of your monitor, in pixels
#A standard monitor is (at least currently) 1080
#Range: > 0
pad_resolution = 720
#When this is true, the minePad is placed off to the side of the screen when held, so it's visible but doesn't take up too much of the screen
#When this is false, the minePad is placed closer to the center of the screen, allow it to be seen better, but taking up more of your view
side_pad = true
#If the left and right buttons should be swapped when using a laser
switch_buttons = false

#AutoVolume makes audio fade off based on distance
#Currently, this seems to not work
[auto_volume]
	#Whether or not auto volume should be enabled
	enabled = true
	#How loud youtube should be by default
	#Range: 0.0 ~ 100.0
	youtube_volume = 100.0
	#Distance after which you can't hear anything (in blocks)
	#Range: 0.0 ~ 1.7976931348623157E308
	dist0 = 18.0
	#Distance after which the sound starts dropping (in blocks)
	#Range: 0.0 ~ 1.7976931348623157E308
	dist100 = 10.0

